# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yottos Tracking Code
email: admin@yottos.com
description: Yottos Tracking Code - JavaScript код отслеживания различных действий на сайте рекламодателя.
# Build settings
theme: jekyll-theme-architect
show_downloads: false
